[package]
name = "hectic-rs"
version = "0.1.0"
authors = ["Ashley Ruglys <ashley.ruglys@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
specs = { version = "0.16.1", default-features = false, features = ["specs-derive"] }
winit = { version = "0.22.1", features = ["web-sys", "serde"] }
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs" }
image = { version = "0.23.4", default-features = false, features = ["png"] }
rand = { version = "0.7.3", features = ["wasm-bindgen"] }
arrayvec = "0.5.1"
futures = "0.3.4"
cgmath = "0.17.0"
zerocopy = "0.3.0"
either = "1.5.3"
wgpu_glyph = { git = "https://github.com/expenses/wgpu_glyph", branch = "experimental" }
env_logger = "0.7.1"
console_error_panic_hook = { version = "0.1.6", optional = true }
web-sys = { version = "0.3.39", optional = true }
wasm-bindgen-futures = { version = "0.4.12", optional = true }
log = "0.4.8"
console_log = "0.2.0"
serde = { version = "1.0.106", features = ["derive"] }
toml = "0.5.6"
line_drawing = "0.8.0"
palette = "0.5.0"
rodio = { git = "https://github.com/alexheretic/rodio", branch = "engineless", default-features = false, features = ["wav"] }
cpal = { git = "https://github.com/expenses/cpal", branch = "webaudio", features = ["wasm-bindgen"] }

[build-dependencies]
yaap = { path = "yaap" }

[features]
default = ["native"]
wasm = [
    "console_error_panic_hook",
    "web-sys",
    "wasm-bindgen-futures",
    "rand/wasm-bindgen",
    "specs/wasm-bindgen",
]
native = ["specs/parallel"]

[patch."https://github.com/RustAudio/cpal.git"]
cpal = { git = "https://github.com/expenses/cpal", branch = "webaudio", features = ["wasm-bindgen"] }
